In [ ]:
# 1. Downloading data
### My data consists of 2016 values for the inequality-adjusted human development index (IHDI) and the raw and log-transformed index of total national scientific publications (scipub) in 2013 and 2015. They together form the basis for my masters thesis which looks to regress country economic and academic development as a factor in international collaboration based on a 2016 survey of academics.

In [91]:
import os
os.getcwd()

'c:\\Users\\rache\\OneDrive\\Documents\\graspp_2025s_fintech'

In [92]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'development_indicator_data_hdi_scipub.csv',
 'development_indicator_data_hdi_scipub.xlsx',
 'development_indicator_data_ihdi.csv',
 'development_indicator_data_scipub.csv',
 'development_indicator_data_scipub.xlsx',
 'Isa_Folder_Test',
 'phdi.csv',
 'phdi.json',
 'RachelHo_HW1.ipynb',
 'racheltest.py',
 'README.md']

In [9]:
import pandas as pd
import numpy as np

In [94]:
df = pd.read_csv("development_indicator_data_ihdi.csv")
df2 = pd.read_csv("development_indicator_data_scipub.csv")

In [96]:
df3 = pd.merge(df, df2, on='country_name')
print(df3)

    country_code_x  i_hdi              country_name  country_code_y    scipub  \
0               12  0.740                 Argentina              12   44008.0
1               13  0.694                   Armenia              13    3166.0
2               17  0.853                 Australia              17  316451.0
3              159  0.845                   Austria             159   81661.0
4               20  0.423                Bangladesh              20    9580.0
..             ...    ...                       ...             ...       ...
90             231  0.652                 Venezuela             231    6034.0
91             234  0.582                   Vietnam             234   12185.0
92              33    NaN  Virgin Islands (British)              33       NaN
93              89  0.297                     Yemen              89     835.0
94             177  0.334                    Zambia             177    1383.0

    scipub_ln
0   10.692127
1    8.060224
2   12.664924
3   11.310332
4    9.167433
..        ...
90   8.705165
91   9.407961
92        NaN
93   6.727432
94   7.232010

[95 rows x 6 columns]

In [90]:
merged_df.head()

,country_code_x,i_hdi,country_name,quartiles_ihdi,dev_IHDI,country_code_y,scipub,scipub_ln
0,12,0.740,Argentina,2.0,0.078131,12,44008.0,10.692127
1,13,0.694,Armenia,1.0,0.032131,13,3166.0,8.060224
2,17,0.853,Australia,3.0,0.191131,17,316451.0,12.664924
3,159,0.845,Austria,3.0,0.183131,159,81661.0,11.310332
4,20,0.423,Bangladesh,0.0,-0.238869,20,9580.0,9.167433

In [98]:
# 2. Manipulating data
### I am grouping the countries by quartiles in terms of IHDI. I am also generating new variables to evaluate how far each country is from the mean value of IHDI.

In [101]:
#### quartiles
df3 ['quartiles_ihdi'] = pd.qcut(df['i_hdi'], q=4, labels=False)

#### deviations
mean_i_hdi = df3['i_hdi'].mean()
print("Mean of IHDI:", mean_i_hdi)
df3 ['dev_IHDI'] = df3['i_hdi'] - mean_i_hdi

merged_df.head()

Mean of IHDI: 0.6618690476190476

,country_code_x,i_hdi,country_name,quartiles_ihdi,dev_IHDI,country_code_y,scipub,scipub_ln
0,12,0.740,Argentina,2.0,0.078131,12,44008.0,10.692127
1,13,0.694,Armenia,1.0,0.032131,13,3166.0,8.060224
2,17,0.853,Australia,3.0,0.191131,17,316451.0,12.664924
3,159,0.845,Austria,3.0,0.183131,159,81661.0,11.310332
4,20,0.423,Bangladesh,0.0,-0.238869,20,9580.0,9.167433